// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr4uU0ESERT39PpaRrS6rUb7zzWg2_zos',
    appId: '1:786979831390:web:37b04fd9e3fff9d53e3ecf',
    messagingSenderId: '786979831390',
    projectId: 'calculators-project',
    authDomain: 'calculators-project.firebaseapp.com',
    storageBucket: 'calculators-project.appspot.com',
    measurementId: 'G-CBH80629GF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaZvpdYEsW-TaLpUCpEwekgAKYjWNE28A',
    appId: '1:786979831390:android:1c38367e67af116e3e3ecf',
    messagingSenderId: '786979831390',
    projectId: 'calculators-project',
    storageBucket: 'calculators-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkneLz6aPJkSXfs1Iq1KZL0soNQfU89OE',
    appId: '1:786979831390:ios:4f1f7eedd54a3ef93e3ecf',
    messagingSenderId: '786979831390',
    projectId: 'calculators-project',
    storageBucket: 'calculators-project.appspot.com',
    iosClientId: '786979831390-t139onr6uoh09h1lt96smc2vuulcoauk.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkneLz6aPJkSXfs1Iq1KZL0soNQfU89OE',
    appId: '1:786979831390:ios:4f1f7eedd54a3ef93e3ecf',
    messagingSenderId: '786979831390',
    projectId: 'calculators-project',
    storageBucket: 'calculators-project.appspot.com',
    iosClientId: '786979831390-t139onr6uoh09h1lt96smc2vuulcoauk.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr4uU0ESERT39PpaRrS6rUb7zzWg2_zos',
    appId: '1:786979831390:web:ff32d9def0d9c89c3e3ecf',
    messagingSenderId: '786979831390',
    projectId: 'calculators-project',
    authDomain: 'calculators-project.firebaseapp.com',
    storageBucket: 'calculators-project.appspot.com',
    measurementId: 'G-24M6H3VRNQ',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAr4uU0ESERT39PpaRrS6rUb7zzWg2_zos',
    appId: '1:786979831390:web:672c9fc5f971e7a63e3ecf',
    messagingSenderId: '786979831390',
    projectId: 'calculators-project',
    authDomain: 'calculators-project.firebaseapp.com',
    storageBucket: 'calculators-project.appspot.com',
    measurementId: 'G-X48CGCNC9R',
  );
}
